In [7]:
# planning block for sentiment model


# VADER -- for overall sentiment categorization AND also sentiment intensity ( 2 features)

In [ ]:
# hypotheses

# both heavinly left and heavily right leaning articles will have more extreme sentiments
# they will also have more extreme negative sentiment expressed regarding the opposing perspective

In [1]:
from data_loader import load_split
import pandas as pd
import numpy as np
import nltk

In [2]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /Users/sarah/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /Users/sarah/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [3]:
data_dir = "/Users/sarah/Documents/SMU/NLP/Article-Bias-Prediction-main/data"

X_train, y_train = load_split(data_dir, "media", "train")
X_val, y_val = load_split(data_dir, "media", "valid")
X_test, y_test = load_split(data_dir, "media", "test")

print(len(X_train), len(X_val), len(X_test))

26590 2356 1300

In [4]:
import feature_extraction_sentiment
from feature_extraction_sentiment import extract_emotionality_features

In [5]:
def build_feature_matrix(texts):
    return np.array([extract_emotionality_features(t) for t in texts])

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

model = LogisticRegression(max_iter=2000, solver = "saga", random_state=42, verbose=1)
model.fit(X_train_scaled, y_train)

val_preds = model.predict(X_val_scaled)

print(classification_report(y_val, val_preds))

In [ ]:
# SAVE FEATURES FOR LATER!!

import numpy as np
import pandas as pd
import joblib

pd.DataFrame(X_train_features).to_csv('X_train_features.csv', index=False)
pd.DataFrame(X_val_features).to_csv('X_val_features.csv', index=False)
pd.DataFrame(y_train, columns=['label']).to_csv('y_train.csv', index=False)
pd.DataFrame(y_val, columns=['label']).to_csv('y_val.csv', index=False)

joblib.dump(model, 'stylometric_model.pkl')

In [6]:
# Now build your matrices
X_train_features = np.array([extract_emotionality_features(t) for t in X_train])
X_val_features = np.array([extract_emotionality_features(t) for t in X_val])
X_test_features = np.array([extract_emotionality_features(t) for t in X_test])

print(f"Train: {X_train_features.shape}")
print(f"Val: {X_val_features.shape}")
print(f"Test: {X_test_features.shape}")

Train: (26590, 11)
Val: (2356, 11)
Test: (1300, 11)

In [ ]:
# SAVE FEATURES FOR LATER!! 8 min processing time. The saved files don't have standardization yet.

pd.DataFrame(X_train_features).to_csv('X_train_features.csv', index=False)
pd.DataFrame(X_val_features).to_csv('X_val_features.csv', index=False)
pd.DataFrame(y_train, columns=['label']).to_csv('y_train.csv', index=False)
pd.DataFrame(y_val, columns=['label']).to_csv('y_val.csv', index=False)

In [8]:
from sklearn.preprocessing import StandardScaler

# Fit scaler on training data only
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_features)

# Transform val and test using the same scaler
X_val_scaled = scaler.transform(X_val_features)
X_test_scaled = scaler.transform(X_test_features)

In [15]:
X_train_features =pd.DataFrame(X_train_features)
X_val_features = pd.DataFrame(X_val_features)
X_test_features = pd.DataFrame(X_test_features)

X_train_features.head()

,0,1,2,3,4,5,6,7,8,9,10
0,-0.9871,0.089,0.103,0.808,-0.033343,0.451420,0.9428,-0.9118,0.000700,0.0,0.000700
1,-0.9542,0.050,0.080,0.870,-0.123158,0.461800,0.7506,-0.8834,0.000000,0.0,0.006702
2,0.9988,0.122,0.062,0.816,0.143974,0.477579,0.9136,-0.8755,0.000604,0.0,0.004225
3,-0.7227,0.028,0.045,0.927,-0.036608,0.389573,0.7579,-0.8402,0.000000,0.0,0.015015
4,0.9982,0.101,0.043,0.856,0.193516,0.428611,0.9158,-0.8689,0.001385,0.0,0.015235

In [17]:
X_train_df.head()

,vader_compound,vader_pos,vader_neg,vader_neu,sent_compound_mean,sent_compound_std,sent_compound_max,sent_compound_min,exclamation_rate,question_rate,caps_word_rate
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
test_features = extract_emotionality_features(X_train[0])
print("Number of features:", len(test_features))
print("Feature values:", test_features)

Number of features: 11
Feature values: [-0.9871, 0.089, 0.103, 0.808, np.float64(-0.03334333333333332), np.float64(0.4514203423147383), 0.9428, -0.9118, 0.0006997900629811056, 0.0, 0.0006997900629811056]

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

model = LogisticRegression(max_iter=2000, solver = "saga", random_state=42, verbose=1)
model.fit(X_train_scaled, y_train)

val_preds = model.predict(X_val_scaled)

print(classification_report(y_val, val_preds))

Epoch 1, change: 1
Epoch 2, change: 0.19836462
Epoch 3, change: 0.12240112
Epoch 4, change: 0.067017722
Epoch 5, change: 0.047872485
Epoch 6, change: 0.027396974
Epoch 7, change: 0.012303961
Epoch 8, change: 0.0084323103
Epoch 9, change: 0.006313945
Epoch 10, change: 0.0035373773
Epoch 11, change: 0.0013437627
Epoch 12, change: 0.00064889757
Epoch 13, change: 0.00046143754
Epoch 14, change: 0.0005173568
Epoch 15, change: 0.00048690311
Epoch 16, change: 0.00046601129
Epoch 17, change: 0.00047287753
Epoch 18, change: 0.00047686859
Epoch 19, change: 0.00047581231
Epoch 20, change: 0.00047116883
Epoch 21, change: 0.00047067711
Epoch 22, change: 0.00046932342
Epoch 23, change: 0.00046763123
Epoch 24, change: 0.00046618545
Epoch 25, change: 0.00046467211
Epoch 26, change: 0.0004636858
Epoch 27, change: 0.00046219938
Epoch 28, change: 0.00046065461
Epoch 29, change: 0.00045939856
Epoch 30, change: 0.00045816247
Epoch 31, change: 0.00045689527
Epoch 32, change: 0.00045533806
Epoch 33, change: 0.00045404356
Epoch 34, change: 0.00045284383
Epoch 35, change: 0.00045136888
Epoch 36, change: 0.00045026027
Epoch 37, change: 0.00044862357
Epoch 38, change: 0.00044745637
Epoch 39, change: 0.00044610618
Epoch 40, change: 0.00044519281
Epoch 41, change: 0.00044318434
Epoch 42, change: 0.00044230681
Epoch 43, change: 0.00044105814
Epoch 44, change: 0.00043950432
Epoch 45, change: 0.00043851349
Epoch 46, change: 0.0004372227
Epoch 47, change: 0.00043584792
Epoch 48, change: 0.00043462518
Epoch 49, change: 0.00043314617
Epoch 50, change: 0.00043196734
Epoch 51, change: 0.000430928
Epoch 52, change: 0.00042919377
Epoch 53, change: 0.00042833689
Epoch 54, change: 0.00042681255
Epoch 55, change: 0.00042579969
Epoch 56, change: 0.00042444788
Epoch 57, change: 0.00042316514
Epoch 58, change: 0.00042196224
Epoch 59, change: 0.00042084513
Epoch 60, change: 0.00041957586
Epoch 61, change: 0.00041806386
Epoch 62, change: 0.00041730226
Epoch 63, change: 0.00041581368
Epoch 64, change: 0.00041468152
Epoch 65, change: 0.00041344136
Epoch 66, change: 0.0004119974
Epoch 67, change: 0.00041115706
Epoch 68, change: 0.00040966982
Epoch 69, change: 0.00040858468
Epoch 70, change: 0.00040724571
Epoch 71, change: 0.00040645535
Epoch 72, change: 0.00040504184
Epoch 73, change: 0.00040359583
Epoch 74, change: 0.00040283749
Epoch 75, change: 0.0004015319
Epoch 76, change: 0.00040006345
Epoch 77, change: 0.00039915507
Epoch 78, change: 0.00039797469
Epoch 79, change: 0.00039666479
Epoch 80, change: 0.00039567434
Epoch 81, change: 0.0003944218
Epoch 82, change: 0.00039325227
Epoch 83, change: 0.00039228041
Epoch 84, change: 0.00039093215
Epoch 85, change: 0.00038990613
Epoch 86, change: 0.00038863677
Epoch 87, change: 0.00038765238
Epoch 88, change: 0.00038650027
Epoch 89, change: 0.00038524501
Epoch 90, change: 0.0003842789
Epoch 91, change: 0.00038301231
Epoch 92, change: 0.0003820264
Epoch 93, change: 0.00038063045
Epoch 94, change: 0.00037989583
Epoch 95, change: 0.00037837934
Epoch 96, change: 0.00037765823
Epoch 97, change: 0.00037624272
Epoch 98, change: 0.00037529646
Epoch 99, change: 0.00037430147
Epoch 100, change: 0.00037299899
Epoch 101, change: 0.00037203455
Epoch 102, change: 0.0003708768
Epoch 103, change: 0.00036970379
Epoch 104, change: 0.00036871499
Epoch 105, change: 0.00036769461
Epoch 106, change: 0.00036647749
Epoch 107, change: 0.00036563878
Epoch 108, change: 0.00036442465
Epoch 109, change: 0.00036336986
Epoch 110, change: 0.00036224569
Epoch 111, change: 0.00036121847
Epoch 112, change: 0.00036011924
Epoch 113, change: 0.00035915875
Epoch 114, change: 0.00035802545
Epoch 115, change: 0.00035691374
Epoch 116, change: 0.00035608594
Epoch 117, change: 0.0003549209
Epoch 118, change: 0.00035404052
Epoch 119, change: 0.00035276694
Epoch 120, change: 0.00035176858
Epoch 121, change: 0.00035084066
Epoch 122, change: 0.00034991939
Epoch 123, change: 0.00034851605
Epoch 124, change: 0.00034778613
Epoch 125, change: 0.00034669648
Epoch 126, change: 0.00034561199
Epoch 127, change: 0.00034463032
Epoch 128, change: 0.00034374732
Epoch 129, change: 0.00034268891
Epoch 130, change: 0.00034176069
Epoch 131, change: 0.00034032528
Epoch 132, change: 0.00033974122
Epoch 133, change: 0.00033856982
Epoch 134, change: 0.00033792061
Epoch 135, change: 0.00033679328
Epoch 136, change: 0.00033543783
Epoch 137, change: 0.00033480816
Epoch 138, change: 0.00033361974
Epoch 139, change: 0.0003327261
Epoch 140, change: 0.00033169103
Epoch 141, change: 0.00033100355
Epoch 142, change: 0.00032983805
Epoch 143, change: 0.00032868114
Epoch 144, change: 0.00032800669
Epoch 145, change: 0.00032686702
Epoch 146, change: 0.00032610944
Epoch 147, change: 0.00032490955
Epoch 148, change: 0.00032414129
Epoch 149, change: 0.00032310321
Epoch 150, change: 0.00032221208
Epoch 151, change: 0.0003213769
Epoch 152, change: 0.0003201447
Epoch 153, change: 0.00031928
Epoch 154, change: 0.00031846506
Epoch 155, change: 0.00031768812
Epoch 156, change: 0.00031651443
Epoch 157, change: 0.00031546238
Epoch 158, change: 0.0003147775
Epoch 159, change: 0.00031403559
Epoch 160, change: 0.00031258499
Epoch 161, change: 0.00031194713
Epoch 162, change: 0.00031104707
Epoch 163, change: 0.00031016706
Epoch 164, change: 0.00030928984
Epoch 165, change: 0.00030825406
Epoch 166, change: 0.00030741181
Epoch 167, change: 0.00030644946
Epoch 168, change: 0.00030568728
Epoch 169, change: 0.00030468873
Epoch 170, change: 0.00030383767
Epoch 171, change: 0.00030290165
Epoch 172, change: 0.00030193434
Epoch 173, change: 0.00030141771
Epoch 174, change: 0.00030017208
Epoch 175, change: 0.00029947067
Epoch 176, change: 0.00029844607
Epoch 177, change: 0.00029777561
Epoch 178, change: 0.00029673614
Epoch 179, change: 0.00029591086
Epoch 180, change: 0.00029493287
Epoch 181, change: 0.00029426684
Epoch 182, change: 0.00029334115
Epoch 183, change: 0.00029241051
Epoch 184, change: 0.00029163714
Epoch 185, change: 0.00029075173
Epoch 186, change: 0.00028997238
Epoch 187, change: 0.00028877729
Epoch 188, change: 0.00028831348
Epoch 189, change: 0.00028741663
Epoch 190, change: 0.00028646979
Epoch 191, change: 0.00028559015
Epoch 192, change: 0.00028494743
Epoch 193, change: 0.00028394551
Epoch 194, change: 0.00028325357
Epoch 195, change: 0.00028235498
Epoch 196, change: 0.00028147873
Epoch 197, change: 0.00028054097
Epoch 198, change: 0.00028000347
Epoch 199, change: 0.00027901222
Epoch 200, change: 0.00027827965
Epoch 201, change: 0.00027741112
Epoch 202, change: 0.00027670994
Epoch 203, change: 0.00027568313
Epoch 204, change: 0.00027489937
Epoch 205, change: 0.00027420869
Epoch 206, change: 0.00027333369
Epoch 207, change: 0.00027275601
Epoch 208, change: 0.00027182032
Epoch 209, change: 0.00027084041
Epoch 210, change: 0.00027024507
Epoch 211, change: 0.00026936259
Epoch 212, change: 0.00026866752
Epoch 213, change: 0.00026786723
Epoch 214, change: 0.00026688979
Epoch 215, change: 0.00026629867
Epoch 216, change: 0.0002656208
Epoch 217, change: 0.00026471273
Epoch 218, change: 0.00026391592
Epoch 219, change: 0.00026301085
Epoch 220, change: 0.00026238352
Epoch 221, change: 0.00026172158
Epoch 222, change: 0.00026081922
Epoch 223, change: 0.00025994736
Epoch 224, change: 0.00025935146
Epoch 225, change: 0.00025862619
Epoch 226, change: 0.00025779657
Epoch 227, change: 0.00025694629
Epoch 228, change: 0.00025635485
Epoch 229, change: 0.00025559761
Epoch 230, change: 0.00025482986
Epoch 231, change: 0.00025397963
Epoch 232, change: 0.00025341561
Epoch 233, change: 0.00025241296
Epoch 234, change: 0.00025191374
Epoch 235, change: 0.00025098028
Epoch 236, change: 0.00025043836
Epoch 237, change: 0.00024950876
Epoch 238, change: 0.00024895829
Epoch 239, change: 0.00024817866
Epoch 240, change: 0.00024733748
Epoch 241, change: 0.00024681868
Epoch 242, change: 0.00024582877
Epoch 243, change: 0.00024532609
Epoch 244, change: 0.00024459614
Epoch 245, change: 0.00024379085
Epoch 246, change: 0.00024309604
Epoch 247, change: 0.000242399
Epoch 248, change: 0.00024169128
Epoch 249, change: 0.00024091413
Epoch 250, change: 0.00024040372
Epoch 251, change: 0.00023946061
Epoch 252, change: 0.00023889708
Epoch 253, change: 0.00023823495
Epoch 254, change: 0.00023756225
Epoch 255, change: 0.00023667681
Epoch 256, change: 0.00023599668
Epoch 257, change: 0.00023546203
Epoch 258, change: 0.00023472717
Epoch 259, change: 0.0002339982
Epoch 260, change: 0.00023337641
Epoch 261, change: 0.0002326388
Epoch 262, change: 0.00023194818
Epoch 263, change: 0.00023123219
Epoch 264, change: 0.0002306936
Epoch 265, change: 0.0002298397
Epoch 266, change: 0.00022942458
Epoch 267, change: 0.0002285093
Epoch 268, change: 0.00022794349
Epoch 269, change: 0.00022720285
Epoch 270, change: 0.00022664048
Epoch 271, change: 0.00022589077
Epoch 272, change: 0.00022519932
Epoch 273, change: 0.00022467249
Epoch 274, change: 0.0002239231
Epoch 275, change: 0.00022327569
Epoch 276, change: 0.00022256315
Epoch 277, change: 0.00022204521
Epoch 278, change: 0.0002214022
Epoch 279, change: 0.00022058595
Epoch 280, change: 0.00021991384
Epoch 281, change: 0.00021954185
Epoch 282, change: 0.0002187674
Epoch 283, change: 0.00021804337
Epoch 284, change: 0.00021749647
Epoch 285, change: 0.00021686049
Epoch 286, change: 0.00021615328
Epoch 287, change: 0.00021547855
Epoch 288, change: 0.00021500737
Epoch 289, change: 0.00021434633
Epoch 290, change: 0.00021366896
Epoch 291, change: 0.00021312005
Epoch 292, change: 0.00021239577
Epoch 293, change: 0.00021186026
Epoch 294, change: 0.00021109222
Epoch 295, change: 0.00021052965
Epoch 296, change: 0.00021002334
Epoch 297, change: 0.00020923838
Epoch 298, change: 0.00020877586
Epoch 299, change: 0.00020812472
Epoch 300, change: 0.00020745819
Epoch 301, change: 0.00020687238
Epoch 302, change: 0.00020621491
Epoch 303, change: 0.00020574651
Epoch 304, change: 0.00020514396
Epoch 305, change: 0.00020431459
Epoch 306, change: 0.00020391646
Epoch 307, change: 0.00020345573
Epoch 308, change: 0.00020263426
Epoch 309, change: 0.00020206427
Epoch 310, change: 0.00020150015
Epoch 311, change: 0.00020080721
Epoch 312, change: 0.00020042991
Epoch 313, change: 0.00019967859
Epoch 314, change: 0.00019908158
Epoch 315, change: 0.00019861229
Epoch 316, change: 0.00019795644
Epoch 317, change: 0.0001974548
Epoch 318, change: 0.00019681531
Epoch 319, change: 0.00019622918
Epoch 320, change: 0.0001956786
Epoch 321, change: 0.0001950669
Epoch 322, change: 0.00019459124
Epoch 323, change: 0.00019397988
Epoch 324, change: 0.00019333763
Epoch 325, change: 0.00019285328
Epoch 326, change: 0.00019231505
Epoch 327, change: 0.00019164232
Epoch 328, change: 0.00019115755
Epoch 329, change: 0.00019047154
Epoch 330, change: 0.00019014997
Epoch 331, change: 0.00018942027
Epoch 332, change: 0.00018896078
Epoch 333, change: 0.00018825634
Epoch 334, change: 0.00018779006
Epoch 335, change: 0.00018729809
Epoch 336, change: 0.00018679599
Epoch 337, change: 0.00018614668
Epoch 338, change: 0.00018555427
Epoch 339, change: 0.00018503194
Epoch 340, change: 0.00018452035
Epoch 341, change: 0.00018396468
Epoch 342, change: 0.00018349888
Epoch 343, change: 0.00018288086
Epoch 344, change: 0.00018233803
Epoch 345, change: 0.00018183979
Epoch 346, change: 0.00018136963
Epoch 347, change: 0.00018076901
Epoch 348, change: 0.00018019178
Epoch 349, change: 0.00017976833
Epoch 350, change: 0.00017920063
Epoch 351, change: 0.00017862851
Epoch 352, change: 0.0001781173
Epoch 353, change: 0.00017761665
Epoch 354, change: 0.00017707759
Epoch 355, change: 0.00017662798
Epoch 356, change: 0.00017606097
Epoch 357, change: 0.00017551996
Epoch 358, change: 0.00017503851
Epoch 359, change: 0.00017454144
Epoch 360, change: 0.00017399035
Epoch 361, change: 0.00017355248
Epoch 362, change: 0.00017294022
Epoch 363, change: 0.00017252195
Epoch 364, change: 0.00017197809
Epoch 365, change: 0.00017145132
Epoch 366, change: 0.00017096756
Epoch 367, change: 0.00017045996
Epoch 368, change: 0.00017004243
Epoch 369, change: 0.00016944756
Epoch 370, change: 0.00016894438
Epoch 371, change: 0.00016852901
Epoch 372, change: 0.00016789484
Epoch 373, change: 0.000167497
Epoch 374, change: 0.0001670082
Epoch 375, change: 0.00016663946
Epoch 376, change: 0.00016594267
Epoch 377, change: 0.00016556254
Epoch 378, change: 0.00016506979
Epoch 379, change: 0.00016456279
Epoch 380, change: 0.0001640482
Epoch 381, change: 0.00016365921
Epoch 382, change: 0.00016311308
Epoch 383, change: 0.00016271338
Epoch 384, change: 0.00016211816
Epoch 385, change: 0.00016174341
Epoch 386, change: 0.00016117501
Epoch 387, change: 0.00016085181
Epoch 388, change: 0.00016019478
Epoch 389, change: 0.00015982245
Epoch 390, change: 0.00015947168
Epoch 391, change: 0.00015879884
Epoch 392, change: 0.00015842707
Epoch 393, change: 0.00015795182
Epoch 394, change: 0.0001575002
Epoch 395, change: 0.00015705109
Epoch 396, change: 0.00015645355
Epoch 397, change: 0.0001562485
Epoch 398, change: 0.00015562376
Epoch 399, change: 0.0001551976
Epoch 400, change: 0.00015467878
Epoch 401, change: 0.00015434628
Epoch 402, change: 0.00015375881
Epoch 403, change: 0.00015341425
Epoch 404, change: 0.00015300506
Epoch 405, change: 0.00015246923
Epoch 406, change: 0.00015198498
Epoch 407, change: 0.00015167926
Epoch 408, change: 0.00015106303
Epoch 409, change: 0.00015077384
Epoch 410, change: 0.0001502299
Epoch 411, change: 0.00014989881
Epoch 412, change: 0.00014931722
Epoch 413, change: 0.00014899684
Epoch 414, change: 0.0001484511
Epoch 415, change: 0.00014810459
Epoch 416, change: 0.00014761344
Epoch 417, change: 0.00014725173
Epoch 418, change: 0.00014677202
Epoch 419, change: 0.00014638565
Epoch 420, change: 0.00014589496
Epoch 421, change: 0.00014554142
Epoch 422, change: 0.0001450694
Epoch 423, change: 0.00014458251
Epoch 424, change: 0.00014424441
Epoch 425, change: 0.00014381419
Epoch 426, change: 0.00014342664
Epoch 427, change: 0.00014289177
Epoch 428, change: 0.00014255891
Epoch 429, change: 0.00014216432
Epoch 430, change: 0.00014170376
Epoch 431, change: 0.00014126305
Epoch 432, change: 0.00014084943
Epoch 433, change: 0.00014051125
Epoch 434, change: 0.00013998685
Epoch 435, change: 0.00013967596
Epoch 436, change: 0.00013922068
Epoch 437, change: 0.0001388199
Epoch 438, change: 0.00013840143
Epoch 439, change: 0.000138086
Epoch 440, change: 0.00013757571
Epoch 441, change: 0.00013724666
Epoch 442, change: 0.00013678435
Epoch 443, change: 0.00013635221
Epoch 444, change: 0.00013603574
Epoch 445, change: 0.00013563526
Epoch 446, change: 0.00013526185
Epoch 447, change: 0.00013476244
Epoch 448, change: 0.00013443343
Epoch 449, change: 0.00013398214
Epoch 450, change: 0.00013363062
Epoch 451, change: 0.00013319524
Epoch 452, change: 0.00013289487
Epoch 453, change: 0.00013248646
Epoch 454, change: 0.00013202451
Epoch 455, change: 0.00013171086
Epoch 456, change: 0.00013121966
Epoch 457, change: 0.000130908
Epoch 458, change: 0.00013056481
Epoch 459, change: 0.00013019316
Epoch 460, change: 0.00012978053
Epoch 461, change: 0.00012939552
Epoch 462, change: 0.00012901471
Epoch 463, change: 0.00012859073
Epoch 464, change: 0.00012827447
Epoch 465, change: 0.00012786968
Epoch 466, change: 0.00012748577
Epoch 467, change: 0.00012711077
Epoch 468, change: 0.00012685233
Epoch 469, change: 0.00012629575
Epoch 470, change: 0.00012609365
Epoch 471, change: 0.00012557861
Epoch 472, change: 0.00012529838
Epoch 473, change: 0.00012492929
Epoch 474, change: 0.00012448773
Epoch 475, change: 0.00012421114
Epoch 476, change: 0.00012378797
Epoch 477, change: 0.00012344962
Epoch 478, change: 0.00012315917
Epoch 479, change: 0.00012268655
Epoch 480, change: 0.00012240135
Epoch 481, change: 0.00012201119
Epoch 482, change: 0.00012163242
Epoch 483, change: 0.00012129791
Epoch 484, change: 0.00012093705
Epoch 485, change: 0.00012060901
Epoch 486, change: 0.00012024568
Epoch 487, change: 0.00011991207
Epoch 488, change: 0.00011950465
Epoch 489, change: 0.00011920544
Epoch 490, change: 0.00011879118
Epoch 491, change: 0.00011844906
Epoch 492, change: 0.00011817627
Epoch 493, change: 0.00011780746
Epoch 494, change: 0.00011746135
Epoch 495, change: 0.00011706521
Epoch 496, change: 0.00011671786
Epoch 497, change: 0.00011651149
Epoch 498, change: 0.00011605965
Epoch 499, change: 0.00011573308
Epoch 500, change: 0.00011540405
Epoch 501, change: 0.00011506868
Epoch 502, change: 0.00011472543
Epoch 503, change: 0.00011435334
Epoch 504, change: 0.00011402363
Epoch 505, change: 0.00011376047
Epoch 506, change: 0.00011338648
Epoch 507, change: 0.00011303021
Epoch 508, change: 0.00011273865
Epoch 509, change: 0.00011245131
Epoch 510, change: 0.00011205469
Epoch 511, change: 0.00011168169
Epoch 512, change: 0.00011146409
Epoch 513, change: 0.00011103621
Epoch 514, change: 0.0001107821
Epoch 515, change: 0.00011039451
Epoch 516, change: 0.0001101158
Epoch 517, change: 0.00010979583
Epoch 518, change: 0.00010943696
Epoch 519, change: 0.00010922332
Epoch 520, change: 0.00010874871
Epoch 521, change: 0.000108521
Epoch 522, change: 0.0001081982
Epoch 523, change: 0.00010786737
Epoch 524, change: 0.00010751131
Epoch 525, change: 0.00010726039
Epoch 526, change: 0.00010692454
Epoch 527, change: 0.00010658918
Epoch 528, change: 0.00010630277
Epoch 529, change: 0.00010600815
Epoch 530, change: 0.0001056992
Epoch 531, change: 0.00010536499
Epoch 532, change: 0.00010501337
Epoch 533, change: 0.00010475438
Epoch 534, change: 0.00010444016
Epoch 535, change: 0.00010418723
Epoch 536, change: 0.00010379286
Epoch 537, change: 0.00010356962
Epoch 538, change: 0.00010319869
Epoch 539, change: 0.00010288893
Epoch 540, change: 0.00010260265
Epoch 541, change: 0.00010232028
Epoch 542, change: 0.00010204797
Epoch 543, change: 0.000101745
Epoch 544, change: 0.00010138085
Epoch 545, change: 0.00010115479
Epoch 546, change: 0.00010084316
Epoch 547, change: 0.00010050638
Epoch 548, change: 0.00010025297
convergence after 549 epochs took 2 seconds
              precision    recall  f1-score   support

           0       0.59      0.20      0.30      1640
           1       0.29      0.09      0.13       618
           2       0.04      0.69      0.08        98

    accuracy                           0.19      2356
   macro avg       0.31      0.33      0.17      2356
weighted avg       0.49      0.19      0.25      2356